DROP TABLE IF EXISTS "Activity_Logs";
DROP SEQUENCE IF EXISTS ACT_LOGS_SEQ CASCADE;

CREATE SEQUENCE ACT_LOGS_SEQ
    INCREMENT 1
    START 1
    MINVALUE 1
    CACHE 1;
CREATE TABLE "Activity_Logs" (
    ACT_ID bigint NOT NULL DEFAULT nextval('ACT_LOGS_SEQ'),
    USER_ID bigint NOT NULL,
    ORDER_DETAIL_ID bigint NOT NULL,
    LATEST_UPDATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ACT_LOG_PKEY PRIMARY KEY (ACT_ID)
);