DROP TABLE IF EXISTS "Orders";
DROP SEQUENCE IF EXISTS ORDERS_SEQ CASCADE;

CREATE SEQUENCE ORDERS_SEQ
    INCREMENT 1
    START 1
    MINVALUE 1
    CACHE 1;
CREATE TABLE "Orders" (
    ORDER_ID bigint NOT NULL DEFAULT nextval('ORDERS_SEQ'),
    POST_ID bigint NOT NULL,
    POSTER_ID bigint NOT NULL,
    FOOD_NAME varchar(255) NOT NULL,
    NOTES varchar(255) NULL,
    QUANTITY bigint NOT NULL,
    ORDER_OWNER_ID bigint NOT NULL,
    STATUS bpchar(1) NULL,
    LATEST_UPDATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ORDER_DETAIL_PKEY PRIMARY KEY (ORDER_ID)
);