DROP TABLE IF EXISTS "Posts";
DROP SEQUENCE IF EXISTS POSTS_SEQ CASCADE;

CREATE SEQUENCE POSTS_SEQ
    INCREMENT 1
    START 1
    MINVALUE 1
    CACHE 1;
CREATE TABLE "Posts" (
    POST_ID bigint NOT NULL DEFAULT nextval('POSTS_SEQ'),
    POSTER_ID bigint NOT NULL,
    QUANTITY bigint NOT NULL,
    START_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    END_DATE timestamp NULL,
    STATUS bpchar(1) NULL,
    CONSTRAINT POST_PKEY PRIMARY KEY (POST_ID)
);