DROP SEQUENCE IF EXISTS USER_SEQ CASCADE;

CREATE SEQUENCE USER_SEQ
    INCREMENT 1
    START 1
    MINVALUE 1
    CACHE 1;

INSERT INTO "Users" (USER_NAME, USER_PASSWORD, USER_TELEPHONE, USER_IMG, USER_CREATED_DATE, USER_CREATED_BY)
VALUES ('Naome', 'password123', '011234', 'user.jpg', CURRENT_TIMESTAMP, '1');
