DROP TABLE IF EXISTS "Users";
DROP SEQUENCE IF EXISTS USER_SEQ CASCADE;

CREATE SEQUENCE USER_SEQ
    INCREMENT 1
    START 1
    MINVALUE 1
    CACHE 1;
CREATE TABLE "Users" (
    USER_ID bigint NOT NULL DEFAULT nextval('USER_SEQ'),
    USER_NAME varchar(255) NOT NULL,
    USER_PASSWORD varchar(255) NOT NULL,
    USER_TELEPHONE varchar(255) NOT NULL,
    USER_IMG varchar(255) NULL,
    USER_CREATED_DATE timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_UPDATED_DATE timestamptz NULL,
    CONSTRAINT USER_PKEY PRIMARY KEY (USER_ID)
);
INSERT INTO "Users" (USER_ID , USER_NAME, USER_PASSWORD, USER_TELEPHONE, USER_IMG, USER_CREATED_DATE)
VALUES (1, 'Naome', 'password123', '011234', 'user.jpg', CURRENT_TIMESTAMP);